-- Migration 095: Add room_specs JSONB to estimates for room-by-room painting
-- Stores the array of room measurements that generated a painting estimate.
-- Existing estimates with the legacy sq_ft/prep_level fields are unaffected.

ALTER TABLE estimates
  ADD COLUMN IF NOT EXISTS room_specs jsonb;

COMMENT ON COLUMN estimates.room_specs IS 'Room-by-room painting spec array. Each element: {name, length_ft, width_ft, ceiling_height_ft, doors, windows, include_ceiling, include_trim, prep_level, paint_supplied_by, paint_grade, primer_needed, dark_to_light}. Generated by the RoomByRoomEditor component. NULL for estimates that used the legacy sq_ft estimator.';
