/**
 * GET  /api/v1/materials  — list saved material prices
 * POST /api/v1/materials  — save a new material price (or bulk upsert)
 */
import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { withAuth } from "@/lib/auth/middleware";
import type { AuthSession } from "@/lib/auth/middleware";
import { query, getPool } from "@/lib/db";
import { logger } from "@/lib/logger";

export const dynamic = "force-dynamic";

const VALID_CATEGORIES = ["paint", "lumber", "hardware", "concrete", "fasteners", "sheet_goods", "trim", "flooring", "other"] as const;

const materialSchema = z.object({
  name: z.string().min(1).max(255),
  brand: z.string().max(100).nullable().optional(),
  category: z.enum(VALID_CATEGORIES).default("other"),
  unit: z.string().min(1).max(50),
  unit_cost_cents: z.number().int().min(0),
  supplier: z.string().max(100).nullable().optional(),
  sku: z.string().max(100).nullable().optional(),
  last_purchased_at: z.string().optional().nullable(),
  notes: z.string().max(500).nullable().optional(),
});

// Bulk upsert: array of items generated by the AI that user wants to save
const bulkSchema = z.object({
  items: z.array(materialSchema).min(1).max(50),
});

export const GET = withAuth(async (request: NextRequest, session: AuthSession) => {
  const { searchParams } = new URL(request.url);
  const category = searchParams.get("category");
  const search = searchParams.get("search");

  const conditions = ["account_id = $1", "is_active = true"];
  const params: unknown[] = [session.accountId];
  let idx = 2;

  if (category && VALID_CATEGORIES.includes(category as typeof VALID_CATEGORIES[number])) {
    conditions.push(`category = $${idx++}`);
    params.push(category);
  }
  if (search) {
    conditions.push(`lower(name) LIKE $${idx++}`);
    params.push(`%${search.toLowerCase()}%`);
  }

  const rows = await query(
    `SELECT id, name, brand, category, unit, unit_cost_cents, supplier, sku, last_purchased_at, notes, updated_at
     FROM materials_price_book
     WHERE ${conditions.join(" AND ")}
     ORDER BY category, name`,
    params
  );

  return NextResponse.json({ data: rows });
});

export const POST = withAuth(async (request: NextRequest, session: AuthSession) => {
  let body: unknown = {};
  try { body = await request.json(); } catch { /* ok */ }

  // Try bulk first, then single
  const bulk = bulkSchema.safeParse(body);
  const items = bulk.success
    ? bulk.data.items
    : (() => {
        const single = materialSchema.safeParse(body);
        if (!single.success) return null;
        return [single.data];
      })();

  if (!items) {
    return NextResponse.json(
      { error: { code: "VALIDATION_ERROR", message: "Invalid body — send a single material or { items: [...] }", traceId: session.traceId } },
      { status: 422 }
    );
  }

  const pool = getPool();
  const client = await pool.connect();
  try {
    await client.query("BEGIN");
    await client.query(
      `SELECT set_config('app.current_user_id', $1, true),
              set_config('app.current_account_id', $2, true),
              set_config('app.current_role', $3, true)`,
      [session.userId, session.accountId, session.role]
    );

    const saved = [];
    for (const item of items) {
      const { rows } = await client.query(
        `INSERT INTO materials_price_book
           (account_id, name, brand, category, unit, unit_cost_cents, supplier, sku, last_purchased_at, notes, created_by)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
         ON CONFLICT DO NOTHING
         RETURNING *`,
        [
          session.accountId,
          item.name,
          item.brand ?? null,
          item.category,
          item.unit,
          item.unit_cost_cents,
          item.supplier ?? null,
          item.sku ?? null,
          item.last_purchased_at ?? null,
          item.notes ?? null,
          session.userId,
        ]
      );
      if (rows[0]) saved.push(rows[0]);
    }

    await client.query("COMMIT");
    return NextResponse.json({ data: saved }, { status: 201 });
  } catch (err) {
    await client.query("ROLLBACK");
    logger.error("POST /api/v1/materials error", err, { traceId: session.traceId });
    return NextResponse.json(
      { error: { code: "INTERNAL_ERROR", message: "Failed to save materials", traceId: session.traceId } },
      { status: 500 }
    );
  } finally {
    client.release();
  }
});
