/**
 * GET  /api/v1/materials  — list saved material prices
 * POST /api/v1/materials  — save a new material price (or bulk upsert)
 */
import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { withAuth } from "@/lib/auth/middleware";
import type { AuthSession } from "@/lib/auth/middleware";
import { query, getPool } from "@/lib/db";
import { logger } from "@/lib/logger";

export const dynamic = "force-dynamic";

const VALID_CATEGORIES = ["paint", "lumber", "hardware", "concrete", "fasteners", "sheet_goods", "trim", "flooring", "other"] as const;

const materialSchema = z.object({
  name: z.string().min(1).max(255),
  brand: z.string().max(100).nullable().optional(),
  category: z.enum(VALID_CATEGORIES).default("other"),
  unit: z.string().min(1).max(50),
  unit_cost_cents: z.number().int().min(0),
  supplier: z.string().max(100).nullable().optional(),
  sku: z.string().max(100).nullable().optional(),
  last_purchased_at: z.string().optional().nullable(),
  notes: z.string().max(500).nullable().optional(),
  // True when this price is an unverified AI guess (e.g. the materials
  // generator's "save to price book" checkbox), not a real receipt-backed
  // purchase. AI guesses must never contribute to avg_paid_cents /
  // purchase_count — that data is reserved for real purchases so it stays
  // trustworthy (see TASK-086 / learnMaterialsFromLineItems).
  is_ai_estimate: z.boolean().optional().default(false),
});

// Bulk upsert: array of items generated by the AI that user wants to save
const bulkSchema = z.object({
  items: z.array(materialSchema).min(1).max(50),
});

export const GET = withAuth(async (request: NextRequest, session: AuthSession) => {
  const { searchParams } = new URL(request.url);
  const category = searchParams.get("category");
  const search = searchParams.get("search");

  const conditions = ["account_id = $1", "is_active = true"];
  const params: unknown[] = [session.accountId];
  let idx = 2;

  if (category && VALID_CATEGORIES.includes(category as typeof VALID_CATEGORIES[number])) {
    conditions.push(`category = $${idx++}`);
    params.push(category);
  }
  if (search) {
    conditions.push(
      `(lower(name) LIKE $${idx} OR lower(coalesce(sku, '')) LIKE $${idx} OR lower(coalesce(supplier, '')) LIKE $${idx})`,
    );
    params.push(`%${search.toLowerCase()}%`);
    idx++;
  }

  const supplier = searchParams.get("supplier");
  if (supplier) {
    conditions.push(`lower(coalesce(supplier, '')) = lower($${idx++})`);
    params.push(supplier);
  }

  const rows = await query(
    `SELECT id, name, brand, category, unit, unit_cost_cents, supplier, sku,
            last_purchased_at, notes, updated_at,
            avg_paid_cents, purchase_count
     FROM materials_price_book
     WHERE ${conditions.join(" AND ")}
     ORDER BY category, name`,
    params
  );

  return NextResponse.json({ data: rows });
});


export const POST = withAuth(async (request: NextRequest, session: AuthSession) => {
  let body: unknown = {};
  try { body = await request.json(); } catch { /* ok */ }

  // Try bulk first, then single
  const bulk = bulkSchema.safeParse(body);
  const items = bulk.success
    ? bulk.data.items
    : (() => {
        const single = materialSchema.safeParse(body);
        if (!single.success) return null;
        return [single.data];
      })();

  if (!items) {
    return NextResponse.json(
      { error: { code: "VALIDATION_ERROR", message: "Invalid body — send a single material or { items: [...] }", traceId: session.traceId } },
      { status: 422 }
    );
  }

  const pool = getPool();
  const client = await pool.connect();
  try {
    await client.query("BEGIN");
    await client.query(
      `SELECT set_config('app.current_user_id', $1, true),
              set_config('app.current_account_id', $2, true),
              set_config('app.current_role', $3, true)`,
      [session.userId, session.accountId, session.role]
    );

    const saved = [];
    for (const item of items) {
      const { rows } = await client.query(
        `INSERT INTO materials_price_book
           (account_id, name, brand, category, unit, unit_cost_cents, supplier, sku,
            last_purchased_at, notes, created_by, avg_paid_cents, purchase_count)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
                 CASE WHEN $12 THEN NULL ELSE $6 END,
                 CASE WHEN $12 THEN 0 ELSE 1 END)
         ON CONFLICT (account_id, lower(name), unit) DO UPDATE SET
           -- unit_cost_cents is "last paid" (migration 162) and rendered as
           -- such in MaterialsCatalogClient — an AI guess must not silently
           -- overwrite a genuine last-paid price on conflict.
           unit_cost_cents   = CASE
             WHEN $12 THEN materials_price_book.unit_cost_cents
             ELSE EXCLUDED.unit_cost_cents
           END,
           brand             = COALESCE(EXCLUDED.brand, materials_price_book.brand),
           supplier          = COALESCE(EXCLUDED.supplier, materials_price_book.supplier),
           sku               = COALESCE(EXCLUDED.sku, materials_price_book.sku),
           last_purchased_at = CASE
             WHEN $12 THEN materials_price_book.last_purchased_at
             ELSE COALESCE(EXCLUDED.last_purchased_at, materials_price_book.last_purchased_at)
           END,
           notes             = COALESCE(EXCLUDED.notes, materials_price_book.notes),
           -- AI-guessed prices (is_ai_estimate = true, param $12) never fold into the
           -- rolling average or increment purchase_count — only real receipt-backed
           -- purchases (the pre-existing default path) do that.
           avg_paid_cents    = CASE
             WHEN $12 THEN materials_price_book.avg_paid_cents
             WHEN materials_price_book.purchase_count <= 0 THEN EXCLUDED.unit_cost_cents
             ELSE ROUND(
               (COALESCE(materials_price_book.avg_paid_cents, materials_price_book.unit_cost_cents)
                 * materials_price_book.purchase_count
                 + EXCLUDED.unit_cost_cents)::numeric
               / (materials_price_book.purchase_count + 1)
             )::int
           END,
           purchase_count    = CASE
             WHEN $12 THEN materials_price_book.purchase_count
             ELSE materials_price_book.purchase_count + 1
           END,
           updated_at        = now()
         RETURNING *`,
        [
          session.accountId,
          item.name,
          item.brand ?? null,
          item.category,
          item.unit,
          item.unit_cost_cents,
          item.supplier ?? null,
          item.sku ?? null,
          item.last_purchased_at ?? null,
          item.notes ?? null,
          session.userId,
          item.is_ai_estimate,
        ]
      );
      if (rows[0]) saved.push(rows[0]);
    }

    await client.query("COMMIT");
    return NextResponse.json({ data: saved }, { status: 201 });
  } catch (err) {
    await client.query("ROLLBACK");
    logger.error("POST /api/v1/materials error", err, { traceId: session.traceId });
    return NextResponse.json(
      { error: { code: "INTERNAL_ERROR", message: "Failed to save materials", traceId: session.traceId } },
      { status: 500 }
    );
  } finally {
    client.release();
  }
});
