services:
  web:
    image: ${WEB_IMAGE:-ghcr.io/your-org/ai-fsm-web}:${APP_TAG:-latest}
    container_name: ai-fsm-web-prod
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      NODE_ENV: production
      APP_PORT: 3000
    ports:
      - "${APP_PORT:-3000}:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/api/health >/dev/null 2>&1 || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 6
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  worker:
    image: ${WORKER_IMAGE:-ghcr.io/your-org/ai-fsm-worker}:${APP_TAG:-latest}
    container_name: ai-fsm-worker-prod
    restart: unless-stopped
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  postgres:
    image: postgres:16
    container_name: ai-fsm-postgres-prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:?required}
      POSTGRES_USER: ${POSTGRES_USER:?required}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?required}
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 15s
      timeout: 5s
      retries: 8
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  redis:
    image: redis:7
    container_name: ai-fsm-redis-prod
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_prod:/data
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "2"

volumes:
  pgdata_prod:
  redis_prod:
